---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(scales)
library(lubridate)
theme_set(theme_light())

source_raw <- read_csv("china-R&D-source.csv")

source_cleaned <- read_csv("china-R&D-source.csv", skip = 25) %>% 
  rename("year" = "No. of Obs", 
         "government" = "18", 
         "enterprise" = "18_1", 
         "foreign" = "17", 
         "others" = "17_1")
  
expenditure_raw <- read_csv("china-R&D-expenditure.csv")

expenditure_cleaned <- read_csv("china-R&D-expenditure.csv", skip = 25) %>% 
  select(-X6, -X14) %>% 
  rename("year" = "No. of Obs", 
         "total" = "30", 
         "basic_research" = "26", 
         "applied_research" = "25", 
         "experimental_development" = "25_1", 
         "manufacturing_industry" = "15", 
         "hightech_industry_total" = "21", 
         "hightech_aircraft-spacecraft" = "17", 
         "hightech_computer" = "19", 
         "hightech_electronic-telecom" = "19_1", 
         "hightech_medical-equip" = "19_2", 
         "hightech_medical-pharma-product" = "19_3", 
         "r&d_institution" = "25_2", 
         "enterprise" = "21_1", 
         "enterprise_large-medium" = "25_3", 
         "higher_education" = "25_4", 
         "other" = "20")
```

```{r}
source_cleaned %>% 
  gather(source, value, -year) %>% 
  ggplot(aes(year, value, color = source)) +
  geom_line(size = 1) +
  scale_x_continuous(limits = c(2002, 2019), 
                     breaks = seq(2001, 2019, 2)) +
  scale_y_continuous(labels = comma) +
  labs(title = "R&D expenditure by sources", 
       x = " ", 
       y = "Expenditure (million yuan)", 
       color = " ", 
       caption = "Data Source: National Bureau of Statistics")
```
```{r}
expenditure_cleaned %>% 
  select(year, total, basic_research, applied_research, experimental_development) %>% 
  mutate(basic_pct = basic_research / total,
         applied_pct = applied_research / total, 
         experimental_pct = experimental_development / total) %>% 
  gather(category, value, basic_research:experimental_development) %>% 
  gather(pct, ratio, basic_pct:experimental_pct) %>% 
  ggplot(aes(year, value, color = category)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = comma) +
  labs(title = "R&D expenditure by research category", 
       x = " ", 
       y = "Expenditure (million yuan)", 
       color = " ", 
       caption = "Data Source: National Bureau of Statistics")
  
```
```{r}
expenditure_cleaned %>% 
  select(year, contains("hightech")) %>% 
  gather(sector, value, -year, -hightech_industry_total) %>% 
  ggplot(aes(year, value, fill = sector)) +
  geom_col()
```
```{r}
expenditure_cleaned
```

