---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
theme_set(theme_light())

china_dprk <- read_csv("High Level Visits.csv") %>% 
  clean_names() %>% 
  separate(date, 
           c("arrival", "departure"), 
           sep = " - ", 
           remove = FALSE, 
           fill = "right") %>% 
  separate(leaders, 
           c("china_leader", "nk_leader"), 
           sep = "/", 
           remove = TRUE)
```

```{r}
library(glue)

china_dprk$departure <- coalesce(china_dprk$departure, china_dprk$arrival)

china_dprk %>% 
  mutate(china_tenure = case_when(china_leader == "Mao Zedong" ~ "1949-1976", 
                                  china_leader == "Deng Xiaoping" ~ "1978-1989", 
                                  china_leader == "Jiang Zemin" ~ "1989-2002", 
                                  china_leader == "Hu Jintao" ~ "2002-2012", 
                                  china_leader == "Xi Jinping" ~ "2012-2020")) %>% 
  count(china_leader, place, china_tenure) %>% 
  mutate(china_leader = glue("{ china_leader } ({ china_tenure })"), 
         china_leader = fct_relevel(china_leader, "Xi Jinping (2012-2020)", "Hu Jintao (2002-2012)", "Jiang Zemin (1989-2002)", "Deng Xiaoping (1978-1989)", "Mao Zedong (1949-1976)")) %>% 
  ggplot(aes(n, china_leader, fill = place)) +
  geom_col() + 
  theme(legend.position = "bottom", 
        plot.title = element_text(face = "bold"), 
        plot.subtitle = element_text(face = "italic")) +
  labs(title = "High-level Visits under Chinese Leaders (1949-2020)", 
       subtitle = "'High-level Visit' is defined as a meeting between Chinese \n and North Korean officials at the level of the Minister of Foreign Affairs or above.",  
       x = "# of Visits", 
       y = " ", 
       fill = "Venue", 
       caption = "Data Source: Cha and Lim 2019")
  
```


